-- CASO 1

-- primer user y rol
CREATE USER PRY2205_USER1
IDENTIFIED BY "PRY2205.semana_8"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

CREATE ROLE PRY2205_ROL_D;

GRANT CREATE TABLE TO PRY2205_ROL_D;
GRANT CREATE VIEW TO PRY2205_ROL_D;
GRANT CREATE SYNONYM TO PRY2205_ROL_D;
GRANT CREATE PUBLIC SYNONYM TO PRY2205_ROL_D;


GRANT CREATE SESSION TO PRY2205_USER1;
GRANT PRY2205_ROL_D TO PRY2205_USER1;

-- segundo user y rol

CREATE USER PRY2205_USER2
IDENTIFIED BY "PRY2205.semana_8_2"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

CREATE ROLE PRY2205_ROL_P;

GRANT CREATE TABLE TO PRY2205_ROL_P;
GRANT CREATE SEQUENCE TO PRY2205_ROL_P;
GRANT CREATE TRIGGER TO PRY2205_ROL_P;


GRANT CREATE ANY SEQUENCE TO PRY2205_USER2;

GRANT CREATE SESSION TO PRY2205_USER2;
GRANT PRY2205_ROL_P TO PRY2205_USER2;
ALTER USER PRY2205_USER2 DEFAULT ROLE PRY2205_ROL_P;

-- sinonimos para los casos desde PRY2205_USER1
CREATE OR REPLACE PUBLIC SYNONYM SYN_ALUMNO                   FOR ALUMNO;
CREATE OR REPLACE PUBLIC SYNONYM SYN_AUTOR                    FOR AUTOR;
CREATE OR REPLACE PUBLIC SYNONYM SYN_CARRERA                  FOR CARRERA;
CREATE OR REPLACE PUBLIC SYNONYM SYN_DETALLE_PRESTAMO_MENSUAL FOR DETALLE_PRESTAMO_MENSUAL;
CREATE OR REPLACE PUBLIC SYNONYM SYN_EDITORIAL                FOR EDITORIAL;
CREATE OR REPLACE PUBLIC SYNONYM SYN_EJEMPLAR                 FOR EJEMPLAR;
CREATE OR REPLACE PUBLIC SYNONYM SYN_EMPLEADO                 FOR EMPLEADO;
CREATE OR REPLACE PUBLIC SYNONYM SYN_ERROR_PROCESO_PRESTAMO   FOR ERROR_PROCESO_PRESTAMO;
CREATE OR REPLACE PUBLIC SYNONYM SYN_ESCUELA                  FOR ESCUELA;
CREATE OR REPLACE PUBLIC SYNONYM SYN_LIBRO                    FOR LIBRO;
CREATE OR REPLACE PUBLIC SYNONYM SYN_PRESTAMO                 FOR PRESTAMO;
CREATE OR REPLACE PUBLIC SYNONYM SYN_REBAJA_MULTA             FOR REBAJA_MULTA;
CREATE OR REPLACE PUBLIC SYNONYM SYN_RESUMEN_PRESTAMO_MENSUAL FOR RESUMEN_PRESTAMO_MENSUAL;
CREATE OR REPLACE PUBLIC SYNONYM SYN_VALOR_MULTA_PRESTAMO     FOR VALOR_MULTA_PRESTAMO;

-- caso 2

-- grant para tablas necesarias desde PRY2205_USER1
GRANT SELECT ON LIBRO TO PRY2205_ROL_P;
GRANT SELECT ON EJEMPLAR TO PRY2205_ROL_P;
GRANT SELECT ON PRESTAMO TO PRY2205_ROL_P;
GRANT SELECT ON EMPLEADO TO PRY2205_ROL_P;

-- usuario 2
CREATE SEQUENCE SEQ_CONTROL_STOCK
START WITH 1
INCREMENT BY 1;

create table CONTROL_STOCK_LIBROS as
select

    SEQ_CONTROL_STOCK.nextval as "ID_CONTROL",
    li.LIBROID as "LIBRO_ID",
       li.NOMBRE_LIBRO as "NOMBRE_LIBRO",
    (SELECT COUNT(*) FROM syn_ejemplar ej WHERE ej.LIBROID = li.LIBROID) as "TOTAL_EJEMPLARES",
    (SELECT COUNT(*) FROM syn_prestamo pre
            join syn_ejemplar ej on pre.ejemplarid = ej.ejemplarid and pre.LIBROID = li.LIBROID
            WHERE ej.LIBROID = li.LIBROID
            AND pre.EMPLEADOID IN (190, 180, 150)
            AND EXTRACT(YEAR FROM pre.FECHA_INICIO) = (EXTRACT(YEAR FROM SYSDATE) - 2)
     ) as "EN_PRESTAMO",
    (SELECT COUNT(pres.EJEMPLARID) FROM SYN_EJEMPLAR E WHERE E.LIBROID = li.LIBROID) -
    (SELECT COUNT(pres.PRESTAMOID)
     FROM SYN_PRESTAMO pres
     WHERE pres.LIBROID = li.LIBROID
      AND pres.EMPLEADOID IN (190, 180, 150)
      AND EXTRACT(YEAR FROM pres.FECHA_INICIO) = (EXTRACT(YEAR FROM SYSDATE) - 2)
    ) as "DISPONIBLES",
    ROUND(((SELECT COUNT(pres.PRESTAMOID)
          FROM SYN_PRESTAMO pres
          WHERE pres.LIBROID = Li.LIBROID
            AND pres.EMPLEADOID IN (190, 180, 150)
            AND EXTRACT(YEAR FROM pres.FECHA_INICIO) = (EXTRACT(YEAR FROM SYSDATE) - 2))
         / NVL((SELECT COUNT(E.EJEMPLARID) FROM SYN_EJEMPLAR E WHERE E.LIBROID = li.LIBROID), 0)) * 100) AS "PORCENTAJE_PRESTAMO",
    CASE
        WHEN ((SELECT COUNT(E.EJEMPLARID) FROM SYN_EJEMPLAR E WHERE E.LIBROID = li.LIBROID) -
            (SELECT COUNT(pres.PRESTAMOID)
             FROM SYN_PRESTAMO pres
             WHERE pres.LIBROID = li.LIBROID
               AND pres.EMPLEADOID IN (190, 180, 150)
               AND EXTRACT(YEAR FROM P.FECHA_INICIO) = (EXTRACT(YEAR FROM SYSDATE) - 2))
        ) > 2 THEN 'S'
        ELSE 'N'
    END AS "STOCK_CRITICO"

from SYN_LIBRO li
WHERE EXISTS (
    SELECT 1
    FROM SYN_PRESTAMO pres
    WHERE pres.LIBROID = li.LIBROID
      AND pres.EMPLEADOID IN (190, 180, 150)
      AND EXTRACT(YEAR FROM pres.FECHA_INICIO) = (EXTRACT(YEAR FROM SYSDATE) - 2)
);

select * from CONTROL_STOCK_LIBROS;

-- caso 3

-- como usuario 1
create or replace view VW_DETALLE_MULTAS as
select
    pre.PRESTAMOID as "ID_PRESTAMO",
    al.NOMBRE || ' ' || al.APATERNO as "NOMBRE_ALUMNO",
    car.DESCRIPCION as "NOMBRE_CARRERA",
    li.LIBROID as "ID_LIBRO",
    TO_CHAR(li.PRECIO, '$999,999,999') as "VALOR_LIBRO",
    TO_CHAR(pre.FECHA_TERMINO, 'DD/MM/YYYY') as "FECHA_TERMINO",
    TO_CHAR(pre.FECHA_ENTREGA, 'DD/MM/YYYY') as "FECHA_ENTREGA",
    (pre.FECHA_ENTREGA - pre.FECHA_TERMINO) as "DIAS_ATRASO",
    TO_CHAR(ROUND(li.PRECIO * 0.03 * (pre.FECHA_ENTREGA - pre.FECHA_TERMINO)), '$999,999,999') AS "VALOR_MULTA",
    NVL(rm.PORC_REBAJA_MULTA, 0) / 100 as "PORCENTAJE_REBAJA_MULTA",
    TO_CHAR(ROUND(
        (li.PRECIO * 0.03 * (pre.FECHA_ENTREGA - pre.FECHA_TERMINO)) -
        ((li.PRECIO * 0.03 * (pre.FECHA_ENTREGA - pre.FECHA_TERMINO)) * (NVL(rm.PORC_REBAJA_MULTA, 0) / 100))
    ), '$999,999,999') as "VALOR_REBAJADO"

FROM SYN_PRESTAMO pre
join SYN_ALUMNO al on pre.ALUMNOID = al.ALUMNOID
join SYN_CARRERA car on al.CARRERAID = car.CARRERAID
join SYN_LIBRO li on pre.LIBROID = li.LIBROID
left join SYN_REBAJA_MULTA rm on car.CARRERAID = rm.CARRERAID

WHERE
    EXTRACT(YEAR FROM pre.FECHA_TERMINO) = (EXTRACT(YEAR FROM SYSDATE) - 2)
    AND pre.FECHA_ENTREGA > pre.FECHA_TERMINO
order by pre.FECHA_ENTREGA desc;

-- indices

CREATE INDEX IDX_PRESTAMO_FECHA_TER ON PRESTAMO(FECHA_TERMINO);
CREATE INDEX IDX_PRESTAMO_ALUMNO ON PRESTAMO(ALUMNOID);
CREATE INDEX IDX_PRESTAMO_LIBRO ON PRESTAMO(LIBROID);
CREATE INDEX IDX_ALUMNO_CARRERA ON ALUMNO(CARRERAID);

